# Generated by Django 2.2.1 on 2019-05-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_auto_20190522_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='status',
            field=models.CharField(choices=[('На работе', 'На работе'), ('В отпуске', 'В отпуске'), ('В командировке', 'В командировке'), ('В Больничном', 'В Больничном')], default='На работе', max_length=15, verbose_name='Статус'),
        ),
    ]
